#!/bin/bash -l 
## Submission script created by clustersub for the young HPC system
## Christopher Keegan, December 2020

#$ -S /bin/bash
#$ -l h_rt=00:15:00
#$ -l mem=1G
#$ -N calculation
#$ -pe mpi 24
#$ -A Imperial_Mat 
#$ -P Gold
#$ -wd /home/mmm0533/Scratch/AulEodsQh60y6 

## Array job treatment
#$ -t 1-2
# Parse parameter file to get variables
number=$SGE_TASK_ID
paramfile=/home/mmm0533/Scratch/AulEodsQh60y6/paramfile.txt

seed="`sed -n ${number}p $paramfile | awk '{print $2}'`"
      
## Load modules
module unload default-modules 
module load gerun
module load compilers/intel/2019/update4
module load mpi/intel/2019/update4/intel
module load castep

#Run calculation
gerun castep.mpi $seed
